[env:gateway]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = jgromes/RadioLib @ ^6.6.0
build_flags = 
    -D ROLE_GATEWAY
    -D NODE_ID=0x01

[env:field]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = jgromes/RadioLib @ ^6.6.0
build_flags = 
    -D NODE_ID=0x02
